apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: GregAWorkflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      ChoiceTest:
        type: choice
        options:
          - Option1
          - Option2
        default: ""
        required: true
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
